language: go

sudo: false

go:
  - 1.7.3

install:
  - go get github.com/codeskyblue/go-sh
  - go get github.com/spf13/viper

script:
  - cd $HOME/gopath/src/github.com/nrechn/mock-travis
  - go test -v ./...

