language: go

sudo: false

go:
  - 1.6.2

matrix:
  allow_failures:
    - go: tip

install:
  - go get github.com/codeskyblue/go-sh
  - go get github.com/fatih/color
  - go get github.com/spf13/viper

script:
  - go test -v ./test/...
  - go build

deploy:
  provider: releases
  api_key: $GITHUBKEY
  file: mock-travis
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
