language: go

sudo: false

go:
  - 1.7.1

install:
  - go get github.com/codeskyblue/go-sh
  - go get github.com/spf13/viper

script:
  - cp -r src test && cp .travis.yml test/ && mv test/mock-travis.go test/mock-travis_test.go && go test -v ./test/...
  - cd src && go build mock-travis.go mock-docker.go common.go

deploy:
  provider: releases
  api_key: $GITHUBKEY
  file: mock-travis
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
