#! -------------------------------------------------------------------------
#! Mock-Travis Settings
#! -------------------------------------------------------------------------

mock_travis:
  # Set docker image which will be utilized.
  docker_image: fedora

  # Set a particular test configuration for mock.
  mock_config: fedora-23-x86_64

  # Set the packages to be tested.
  # Packages directory.
  # For example
  #         If the PACKAGE spec file is stored like this
  #         ├───GitHub Repository
  #         │   └───rpm
  #         │       └───build
  #         │           └───PACKAGE
  #         │               └───PACKAGE.spec
  #         The directory should be set to `./rpm/build` or `rpm/build`.
  #
  #         If the PACKAGE spec file is stored like this
  #         ├───GitHub Repository
  #         │   └───PACKAGE
  #         │       └───PACKAGE.spec
  #         The directory should be set to `./` or leave it empty.
  packages_directory: ./
  # Target packages.
  # It is allowed to set multiple package name in one line.
  packages_name: 
  # Build requires of target package.
  # It is allowed to set multiple package name in one line.
  # Set here will force script to ignore the `git` below.
  packages_buildrequires: 
  # Use RPM spec files from a GitHub repository
  # instead of storing in local.
  # It only works if the `buildrequires` above is empty.
  # Otherwise, script will use `buildrequires` and ignore the `git`.
  # For example
  #         If your spec repository is 
  #         "https://github.com/nrechn/Sway-Fedora",
  #         git could be set to `nrechn/Sway-Fedora`
  packages_buildrequires_git: 
  # Use extra/external repository during building packages.
  # This option allows mock to access an additional repository
  # plus defaults repositories based on the mock config.
  # gpgcheck is disabled in this option.
  # For example
  #         If add FZUG as an extra repository
  #         packages_extra_repo should set to
  #         "https://repo.fdzh.org/FZUG/testing/24/x86_64/"
  packages_extra_repo:



#! -------------------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
#! -------------------------------------------------------------------------

sudo: required

services:
  - docker

script:
  - wget -q https://github.com/nrechn/mock-travis/releases/download/latest/mock-travis 
        && chmod +x mock-travis 
        && ./mock-travis
